### ISSUE TITLE
Icon is missing on resume from sleep

### ISSUE THREAD

**Issue by ImDevinC** [ImDevinC/StreamControllerDiscordPlugin#13]
From Discord:
> @Daisuke88
> plugin working great, even after suspend. However, I noticed that the icon disappears when the PC wakes but returns on press. Is this normal??

Also missing on first startup

**Comment by ImDevinC** [comment]
Should now be resolved with #15

**Comment by purpledalek** [comment]
unfortunately, #15 hasn't fixed it for my stream deck mini, i'm still having the same issue as before

**Comment by purpledalek** [comment]
unfortunately #15 doesn't seem to have fixed the issue for me, im still having the same problems as before even after updating the plugin
